# Generated by Django 2.1.5 on 2019-02-04 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photovault', '0005_auto_20190204_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomedia',
            name='accessRights',
            field=models.TextField(default='private'),
        ),
        migrations.AddField(
            model_name='photomedia',
            name='caption',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='photomedia',
            name='dateUpload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='photomedia',
            name='filePath',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='photomedia',
            name='fileType',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='photomedia',
            name='hashtag',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='photomedia',
            name='location',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='photomedia',
            name='userEmail',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AddField(
            model_name='photomedia',
            name='userId',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
