# Generated by Django 2.1.5 on 2019-02-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovault', '0009_photomedia_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomedia',
            name='isPublic',
            field=models.TextField(default='null'),
        ),
    ]
