apiVersion: apps/v1
kind: Deployment
metadata:
  name: explore
  labels:
   app: explore
   kube-monkey/enabled: "enabled"
   kube-monkey/identifier: "explore"
   kube-monkey/mtbf: '2'
   kube-monkey/kill-mode: "fixed"
   kube-monkey/kill-value: "1"  
spec:
  replicas: 3
  selector:
   matchLabels:
    app: explore
  template:
    metadata:
      labels:
        app: explore
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "explore"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
    spec:
      containers:
      - name: explore
        image: photovault/exploreimages
        imagePullPolicy: Always
        ports:
        - containerPort: 6060
---
kind: Service
apiVersion: v1
metadata:
  name: explore
spec:
  type: LoadBalancer
  selector:
   app: explore
  ports:
  - protocol: TCP
    port: 6060
    targetPort: 6060
    nodePort: 30003
