apiVersion: apps/v1
kind: Deployment
metadata:
 name: loginsearch-blue
 labels:
  app: loginsearch
  kube-monkey/enabled: "enabled"
  kube-monkey/identifier: "loginsearch"
  kube-monkey/mtbf: '2'
  kube-monkey/kill-mode: "fixed"
  kube-monkey/kill-value: "1"
spec:
 replicas: 5
 selector:
  matchLabels:
   app: loginsearch
 template:
  metadata:
   labels:
    app: loginsearch
    kube-monkey/enabled: "enabled"
    kube-monkey/identifier: "loginsearch"
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
    color: blue
  spec:
   containers:
   - name: loginsearch
     image: photovault/loginsearch
     imagePullPolicy: Always
     ports:
     - containerPort: 5000
