apiVersion: apps/v1
kind: Deployment
metadata:
 name: loginsearch
 labels:
  app: loginsearch
  kube-monkey/enabled: "enabled"
  kube-monkey/identifier: "loginsearch"
  kube-monkey/mtbf: '2'
  kube-monkey/kill-mode: "fixed"
  kube-monkey/kill-value: "1"
spec:
 replicas: 3
 selector:
  matchLabels:
   app: loginsearch
 template:
  metadata:
   labels:
    app: loginsearch
    kube-monkey/enabled: "enabled"
    kube-monkey/identifier: "loginsearch"
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
  spec:
   containers:
   - name: loginsearch
     image: photovault/loginsearch:v11
     imagePullPolicy: Always
     ports:
     - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
 name: loginsearch
spec:
 type: LoadBalancer
 selector:
  app: loginsearch
 ports:
 - protocol: TCP
   targetPort: 5000
   port: 5000
   nodePort: 30002

