apiVersion: apps/v1
kind: Deployment
metadata:
 name: loginsearch
 labels:
  app: loginsearch
spec:
 replicas: 3
 selector:
  matchLabels:
   app: loginsearch
 template:
  metadata:
   labels:
    app: loginsearch
  spec:
   containers:
   - name: loginsearch
     image: photovault/loginsearch:v11
     imagePullPolicy: Always
     ports:
     - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
 name: loginsearch
spec:
 type: NodePort
 selector:
  app: loginsearch
 ports:
 - protocol: TCP
   targetPort: 5000
   port: 5000
   nodePort: 30002
