apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: upload
  labels:
    app: upload
    kube-monkey/enabled: "enabled"
    kube-monkey/identifier: "upload"
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: upload
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "upload"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
    spec:
      containers:
      - name: upload
        image: photovault/upload
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: upload
  labels:
    run: upload
spec:
  selector:
    run: upload
  ports:
  - protocol: TCP
    targetPort: 8000
    port: 8000
    name: http
    nodePort: 30004
  type: LoadBalancer
