apiVersion: apps/v1
kind: Deployment
metadata:
 name: website-blue
 labels:
  app: website
  kube-monkey/enabled: "enabled"
  kube-monkey/identifier: "website"
  kube-monkey/mtbf: '2'
  kube-monkey/kill-mode: "fixed"
  kube-monkey/kill-value: "1"  
spec:
  replicas: 5
  selector:
   matchLabels:
    app: website
  template:
    metadata:
      labels:
        app: website
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "website"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
        color: blue
    spec:
     containers:
     - name: website
       image: photovault/website
       imagePullPolicy: Always
       ports:
       - containerPort: 30001

