apiVersion: apps/v1
kind: Deployment
metadata:
 name: website-deployment
 labels:
  app: website
spec:
 replicas: 3
 selector:
  matchLabels:
   app: website
 template:
  metadata:
   labels:
    app: website
  spec:
   containers:
   - name: website
     image: photovault/website:v10
     imagePullPolicy: Always
     ports:
     - containerPort: 30001

---
kind: Service
apiVersion: v1
metadata:
 name: website
spec:
 type: NodePort
 selector:
  app: website
 ports:
 - protocol: TCP
   port: 30001
   targetPort: 30001
   nodePort: 30001
