apiVersion: apps/v1
kind: Deployment
metadata:
 name: website
 labels:
  app: website
  kube-monkey/enabled: "enabled"
  kube-monkey/identifier: "website"
  kube-monkey/mtbf: '2'
  kube-monkey/kill-mode: "fixed"
  kube-monkey/kill-value: "1"  
spec:
  replicas: 3
  selector:
   matchLabels:
    app: website
  template:
    metadata:
      labels:
        app: website
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "website"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
    spec:
     containers:
     - name: website
       image: photovault/website
       imagePullPolicy: Always
       ports:
       - containerPort: 30001

---
kind: Service
apiVersion: v1
metadata:
 name: website
spec:
 type: LoadBalancer
 selector:
  app: website
 ports:
 - protocol: TCP
   port: 30001
   targetPort: 30001
   nodePort: 30001
