# Generated by Django 2.1.5 on 2019-02-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photovault', '0004_auto_20190204_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomedia',
            name='accessRights',
        ),
        migrations.RemoveField(
            model_name='photomedia',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='photomedia',
            name='dateUpload',
        ),
        migrations.RemoveField(
            model_name='photomedia',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='photomedia',
            name='fileType',
        ),
        migrations.RemoveField(
            model_name='photomedia',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='photomedia',
            name='location',
        ),
        migrations.RemoveField(
            model_name='photomedia',
            name='userEmail',
        ),
        migrations.RemoveField(
            model_name='photomedia',
            name='userId',
        ),
    ]
