# Generated by Django 2.1.5 on 2019-02-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovault', '0006_auto_20190204_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomedia',
            name='thumbnailLink',
            field=models.TextField(default='null'),
        ),
    ]
