# Generated by Django 2.1.5 on 2019-02-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovault', '0007_photomedia_thumbnaillink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photomedia',
            old_name='thumbnailLink',
            new_name='thumbnailHeight',
        ),
        migrations.AddField(
            model_name='photomedia',
            name='thumbnailwidth',
            field=models.TextField(default='null'),
        ),
    ]
