# Generated by Django 2.1.5 on 2019-02-02 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('fileName', models.TextField()),
                ('downloadLink', models.TextField()),
                ('filePath', models.TextField()),
                ('accessRights', models.TextField()),
                ('caption', models.TextField()),
                ('hashtag', models.TextField()),
                ('size', models.TextField()),
                ('dateUpload', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.TextField()),
                ('fileType', models.TextField()),
            ],
        ),
    ]
