# Generated by Django 2.1.5 on 2019-02-04 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photovault', '0003_auto_20190204_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='null', max_length=100)),
                ('userEmail', models.EmailField(default='null', max_length=254)),
                ('fileName', models.TextField()),
                ('downloadLink', models.TextField()),
                ('filePath', models.TextField(default='null')),
                ('accessRights', models.TextField(default='private')),
                ('caption', models.TextField(default='null')),
                ('hashtag', models.TextField(default='null')),
                ('size', models.TextField()),
                ('dateUpload', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.TextField(default='null')),
                ('fileType', models.TextField(default='null')),
            ],
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
