# Generated by Django 2.1.5 on 2019-02-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photovault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='accessRights',
        ),
        migrations.RemoveField(
            model_name='media',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='media',
            name='dateUpload',
        ),
        migrations.RemoveField(
            model_name='media',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='media',
            name='fileType',
        ),
        migrations.RemoveField(
            model_name='media',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='media',
            name='location',
        ),
        migrations.RemoveField(
            model_name='media',
            name='userEmail',
        ),
        migrations.RemoveField(
            model_name='media',
            name='userId',
        ),
    ]
